_version:
  desc: 项目版本处理
  cmds:
    - echo "package version" > {{.VersionFile}}
    - echo 'const Version = "{{.Version}}"' >> {{.VersionFile}}
    - echo 'const BuildVersion = "{{.BuildVersion}}"' >> {{.VersionFile}}
    - echo 'const GitCommit = "{{.GitCommit}}"' >> {{.VersionFile}}

build:
  desc: 编译应用
  deps: [_version]
  cmds:
    - GOBIN=`pwd` go install main.go

dev:
  desc: 编译应用
  cmds:
    - ./main node

build_linux:
  desc: 交叉编译成linux应用
  deps: [_version]
  cmds:
    - GOBIN=`pwd` CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go install main.go

docker_build:
  desc: 构建docker镜像
  deps: [build_linux]
  vars:
    ImageCommitName: "kchain:{{.Version}}_{{.GitCommit}}"
  cmds:
    - docker build -t {{.ImageName}} .
    - docker tag {{.ImageName}} {{.ImagesPrefix}}{{.ImageName}}
    - docker tag {{.ImageName}} {{.ImagesPrefix}}{{.ImageCommitName}}
    - docker tag {{.ImageName}} {{.ImagesPrefix}}{{.ImageNameTest}}

docker_push_dev:
  desc: docker push test
  deps: [docker_build]
  vars:
      ImageCommitName: "kchain:{{.Version}}_{{.GitCommit}}"
  cmds:
      - docker push {{.ImagesPrefix}}{{.ImageNameTest}}

docker_push_pro:
  desc: docker push pro
  deps: [docker_build]
  vars:
      ImageCommitName: "kchain:{{.Version}}_{{.GitCommit}}"
  cmds:
      - docker push {{.ImagesPrefix}}{{.ImageCommitName}}
      - docker push {{.ImagesPrefix}}{{.ImageName}}

rm_stop:
  desc: 删除所有的的容器
  cmds:
    - sudo docker rm -f $(sudo docker ps -qa)
    - sudo docker ps -a

docker_test:
  desc: kchain docker test
  cmds:
    - ls * | grep example_data || mkdir example_data
    - docker run --rm -it -v `pwd`/example_data:/kdata -p 46656:46656 -p 46657:46657 kchain init
    - docker run --rm -it -v `pwd`/example_data:/kdata -p 46656:46656 -p 46657:46657 kchain


test_clear:
  desc: 删除文件
  cmds:
    - ./main --home test/d1 unsafe_reset_all
    - ./main --home test/d2 unsafe_reset_all
    - ./main --home test/d3 unsafe_reset_all
    - ./main --home test/d4 unsafe_reset_all
    - ./main --home test/d5 unsafe_reset_all
    - ./main --home test/d6 unsafe_reset_all

docker_login:
  desc: 登陆镜像仓库
  cmds:
    - docker login -u baiyunhui@yuanben -p ybl12345 registry.cn-hangzhou.aliyuncs.com

test_rm:
  desc: 删除文件
  cmds:
    - rm -rf test/d1
    - rm -rf test/d2
    - rm -rf test/d3
    - rm -rf test/d4
    - rm -rf test/d5
    - rm -rf test/d6

test_create:
  desc: 删除文件
  cmds:
    - ./main --home test/d1 init
    - ./main --home test/d2 init
    - ./main --home test/d3 init
    - ./main --home test/d4 init
    - ./main --home test/d5 init
    - ./main --home test/d6 init
